vscode_version = "1.97.0"

[[extensions]]
publisher_name = "ms-vscode-remote"
extension_name = "remote-ssh"
[[extensions]]
publisher_name = "mikestead"
extension_name = "dotenv"
[[extensions]]
publisher_name = "mobalic"
extension_name = "jetbrains-dark-theme"
[[extensions]]
publisher_name = "eamodio"
extension_name = "gitlens"
[[extensions]]
publisher_name = "donjayamanne"
extension_name = "githistory"
[[extensions]]
publisher_name = "oderwat"
extension_name = "indent-rainbow"
[[extensions]]
publisher_name = "wayou"
extension_name = "vscode-todo-highlight"
[[extensions]]
publisher_name = "rodrigocfd"
extension_name = "format-comment"
[[extensions]]
publisher_name = "signageos"
extension_name = "signageos-vscode-sops"
[[extensions]]
publisher_name = "continue"
extension_name = "continue"
[[extensions]]
publisher_name = "mkhl"
extension_name = "direnv"
[[extensions]]
publisher_name = "pkief"
extension_name = "material-icon-theme"
[[extensions]]
publisher_name = "editorconfig"
extension_name = "editorconfig"
[[extensions]]
publisher_name = "be5invis"
extension_name = "vscode-custom-css"
[[extensions]]
publisher_name = "tamasfe"
extension_name = "even-better-toml"
[[extensions]]
publisher_name = "kamadorueda"
extension_name = "alejandra"
[[extensions]]
publisher_name = "jnoortheen"
extension_name = "nix-ide"
[[extensions]]
publisher_name = "skellock"
extension_name = "just"
[[extensions]]
publisher_name = "arr"
extension_name = "marksman"
[[extensions]]
publisher_name = "bluebrown"
extension_name = "yamlfmt"
[[extensions]]
publisher_name = "fnando"
extension_name = "linter"
[[extensions]]
publisher_name = "bluebrown"
extension_name = "yamlfmt"
[[extensions]]
publisher_name = "esbenp"
extension_name = "prettier-vscode"
[[extensions]]
publisher_name = "mtxr"
extension_name = "sqltools"
[[extensions]]
publisher_name = "ms-dotnettools"
extension_name = "csharp"
[[extensions]]
publisher_name = "ms-dotnettools"
extension_name = "csdevkit"
[[extensions]]
publisher_name = "ms-dotnettools"
extension_name = "vscode-dotnet-runtime"
[[extensions]]
publisher_name = "csharpier"
extension_name = "csharpier-vscode"
[[extensions]]
publisher_name = "rust-lang"
extension_name = "rust-analyzer"
# NOTE: This does not work with nix4vscode -- using nix-vscode-extensions instead
# [[extensions]]
# publisher_name = "vadimcn"
# extension_name = "vscode-lldb"
[[extensions]]
publisher_name = "fill-labs"
extension_name = "dependi"
[[extensions]]
publisher_name = "usernamehw"
extension_name = "errorlens"
[[extensions]]
publisher_name = "gruntfuggly"
extension_name = "todo-tree"
[[extensions]]
publisher_name = "gofenix"
extension_name = "go-lines"
[[extensions]]
publisher_name = "golang"
extension_name = "go"
[[extensions]]
publisher_name = "neikeq"
extension_name = "godot-csharp-vscode"
[[extensions]]
publisher_name = "RooVeterinaryInc"
extension_name = "roo-cline"
[[extensions]]
publisher_name = "gaborv"
extension_name = "flatbuffers"
[[extensions]]
publisher_name = "vscodevim"
extension_name = "vim"
